### ISSUE TITLE
!MESSAGE Evaluator actor crashed 

### ISSUE THREAD

**Issue by MridulMishra** [scala-ide/scala-worksheet#218]
Hi,
    The Scala worksheet on Eclipse Luna does not evaluate i.e. displays no results when saved.  I am on Mac OS X 10.8.5. The error in workspace log is as below:

!ENTRY org.scala-ide.sdt.core 4 0 2015-04-22 11:57:58.369
!MESSAGE Evaluator actor crashed 
!STACK 0
java.lang.LinkageError: scala/tools/nsc/interactive/Response
	at org.scalaide.worksheet.runtime.SourceInstrumenter$$anonfun$1$$anonfun$apply$1.apply(SourceInstrumenter.scala:32)
	at org.scalaide.core.compiler.IScalaPresentationCompiler$.withResponse(IScalaPresentationCompiler.scala:308)
	at org.scalaide.worksheet.runtime.SourceInstrumenter$$anonfun$1.apply(SourceInstrumenter.scala:32)
	at org.scalaide.worksheet.runtime.SourceInstrumenter$$anonfun$1.apply(SourceInstrumenter.scala:29)
	at org.scalaide.core.internal.compiler.PresentationCompilerProxy$$anonfun$internal$1.apply(PresentationCompilerProxy.scala:105)
	at org.scalaide.core.internal.compiler.PresentationCompilerProxy$$anonfun$internal$1.apply(PresentationCompilerProxy.scala:104)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalaide.core.internal.compiler.PresentationCompilerProxy.internal(PresentationCompilerProxy.scala:104)
	at org.scalaide.core.internal.compiler.PresentationCompilerProxy.apply(PresentationCompilerProxy.scala:62)
	at org.scalaide.worksheet.runtime.SourceInstrumenter.instrumentProgram(SourceInstrumenter.scala:29)
	at org.scalaide.worksheet.runtime.SourceInstrumenter.instrument(SourceInstrumenter.scala:22)
	at org.scalaide.worksheet.runtime.WorksheetRunner$$anonfun$act$1$$anonfun$apply$1.applyOrElse(WorksheetRunner.scala:62)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.actors.ReactorTask.run(ReactorTask.scala:31)
	at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by dotta** [comment]
`LinkageError` means that there is a binary incompatibility. Could you create and share a small project that can be used to reproduce the issue?

**Comment by MridulMishra** [comment]
Thanks Mirco. There is not much in project, I Just downloaded the worksheet and was trying to run some sample code. Could it be because of compatibility of components from anyone pasted below?
![screenshot](https://cloud.githubusercontent.com/assets/2775737/7269246/c144374a-e8ef-11e4-959b-8977caed67e8.png)

**Comment by dotta** [comment]
Your installation seems fine, but I can't guarantee it isn't broken.

So, you have an empty project? No dependencies? If so, maybe try creating a new workspace (though I'd be really surprised this is the reason for the described issue...)

**Comment by MridulMishra** [comment]
That's correct. Empty project with no dependency. Tried new workspace but no luck. I installed worksheet separately than IDE. Could that be the problem. Somehow IDE installation on Luna did not bring worksheet.

**Comment by dotta** [comment]
That may be the problem indeed :-)

What are the update site you have used for installing the Scala IDE and Worksheet?

Also, to avoid these sort of installation hiccups, did you know download the SDK (http://scala-ide.org/download/sdk.html).

**Comment by MridulMishra** [comment]
yeah, I thought i don't need Eclipse Lune again which seems to come bundled with the SDK. Any way let me try that instead of breaking my head on it :)

**Comment by dotta** [comment]
> yeah, I thought i don't need Eclipse Luna again which seems to come bundled with the SDK. 
I'm not following :-)

> Any way let me try that instead of breaking my head on it :)
Sure. But, let us know what are the update-sites you have used to end up with the problem described in the ticket. Just want to make sure there is nothing wrong, and the broken state of your installation is "expected".
