### ISSUE TITLE
Worksheet works with Scala 2.12 but not 2.10 and 2.11

### ISSUE THREAD

**Issue by DungxNguyen** [scala-ide/scala-worksheet#234]
When I set the scalar compiler version using Scala 2.10, worksheet doesn't produce any result. This is the part of the log file. The same worksheet runs well with Scala 2.12
`2017-07-19 10:19:37,136 DEBUG [main] - PresentationCompilerProxy - Restarting presentation compiler. The following units will be reloaded: List(hellows.sc)
2017-07-19 10:19:37,137 DEBUG [main] - PresentationCompilerActivityListener - Stopping PresentationCompilerActivityListener for project myworksheet
2017-07-19 10:19:37,137  INFO [main] - ScalaPresentationCompiler - shutting down presentation compiler on project: myworksheet
2017-07-19 10:19:37,184 DEBUG [main] - PresentationCompilerProxy - Presentation compiler settings for myworksheet:
  -bootclasspath = /home/dnguyen/ScalaIDE/eclipse/plugins/org.scala-ide.scala211.jars_4.6.1.201706090853/target/jars/scala-library.jar
  -classpath = /home/dnguyen/workspace2/myworksheet/bin:/home/dnguyen/ScalaIDE/eclipse/plugins/org.scala-ide.scala211.jars_4.6.1.201706090853/target/jars/scala-reflect.jar:/home/dnguyen/ScalaIDE/eclipse/plugins/org.scala-ide.scala211.jars_4.6.1.201706090853/target/jars/scala-library.jar
  -d = .
  -deprecation = false
  -encoding = UTF-8
  -javabootclasspath = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/dnsns.jar
  -javaextdirs =  
  -sourcepath = /home/dnguyen/workspace2/myworksheet/src
  -unchecked = false
  -verbose = false
  -Xexperimental = false
  -Xfuture = false
  -Ymacro-expand = discard
  -Ypartial-unification = false
  -Ypresentation-debug = false
  -Ypresentation-delay = 0
  -Ypresentation-verbose = false
2017-07-19 10:19:37,184 DEBUG [main] - PresentationCompilerActivityListener - Starting PresentationCompilerActivityListener for project myworksheet
2017-07-19 10:19:37,185  INFO [main] - ScalaPresentationCompiler - Clearing doc comments (0 entries)
2017-07-19 10:19:38,905  INFO [org.eclipse.jface.text.reconciler.MonoReconciler] - ScalaPresentationCompiler - Clearing doc comments (0 entries)
2017-07-19 10:19:38,905  INFO [org.eclipse.jface.text.reconciler.MonoReconciler] - ScalaPresentationCompiler - Flushed hellows.sc
2017-07-19 10:19:39,366  INFO [bundle-330-ActorSystem-akka.actor.default-dispatcher-16] - ScalaPresentationCompiler - Clearing doc comments (0 entries)
2017-07-19 10:19:39,374 DEBUG [bundle-330-ActorSystem-akka.actor.default-dispatcher-16] - ResidentCompiler - compiling /home/dnguyen/workspace2/myworksheet/.worksheet/src/myfirstws.hellows.scala
2017-07-19 10:19:39,430  INFO [bundle-330-ActorSystem-akka.actor.default-dispatcher-16] - ResidentCompiler - compiling: List(/home/dnguyen/workspace2/myworksheet/.worksheet/src/myfirstws.hellows.scala)
2017-07-19 10:19:39,581 DEBUG [bundle-330-ActorSystem-akka.actor.default-dispatcher-16] - System.out - [ERROR] [07/19/2017 10:19:39.580] [bundle-330-ActorSystem-akka.actor.default-dispatcher-22] [akka://bundle-330-ActorSystem/user/worksheet-runtime/worksheet-manager/worksheet-runner-for-project-myworksheet] None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.$anonfun$mkLambdaMetaFactoryCall$4(Delambdafy.scala:92)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.mkLambdaMetaFactoryCall(Delambdafy.scala:92)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transformFunction(Delambdafy.scala:258)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:265)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:56)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1370)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:293)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:56)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformTrees$1(Trees.scala:2559)
	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1351)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:293)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:56)
	at scala.reflect.internal.Trees.$anonfun$itransform$2(Trees.scala:1367)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1365)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:293)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:56)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1408)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:40)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:279)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:56)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
	at scala.reflect.internal.Trees.$anonfun$itransform$4(Trees.scala:1412)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1411)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:293)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:56)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
	at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1430)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1430)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:293)
	at scala.tools.nsc.transform.Delambdafy$DelambdafyTransformer.transform(Delambdafy.scala:56)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:423)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:416)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:387)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:387)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:387)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1427)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1412)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1407)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1501)
	at org.scalaide.worksheet.runtime.ResidentCompiler.runCompilation(ResidentCompiler.scala:58)
	at org.scalaide.worksheet.runtime.ResidentCompiler.compile(ResidentCompiler.scala:42)
	at org.scalaide.worksheet.runtime.WorksheetRunner$$anonfun$receive$1.applyOrElse(WorksheetRunner.scala:76)
	at akka.actor.Actor.aroundReceive(Actor.scala:497)
	at akka.actor.Actor.aroundReceive$(Actor.scala:495)
	at org.scalaide.worksheet.runtime.WorksheetRunner.aroundReceive(WorksheetRunner.scala:44)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
2017-07-19 10:19:39,581 DEBUG [bundle-330-ActorSystem-akka.actor.default-dispatcher-22] - WorksheetRunner - Shutted down worksheet runner for project `myworksheet`.
`2017-07-19 10:19:39,581 DEBUG [bundle-330-ActorSystem-akka.actor.default-dispatcher-16] - System.out - at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-07-19 10:19:39,584 DEBUG [bundle-330-ActorSystem-akka.actor.default-dispatcher-22] - ResidentCompiler$ - Compilation arguments: -javabootclasspath
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-7.b12.fc26.x86_64/jre/lib/ext/dnsns.jar
-javaextdirs
 
-bootclasspath
/home/dnguyen/ScalaIDE/eclipse/plugins/org.scala-ide.scala211.jars_4.6.1.201706090853/target/jars/scala-library.jar
-encoding
UTF-8
-classpath
/home/dnguyen/ScalaIDE/eclipse/configuration/org.eclipse.osgi/330/0/.cp/target/lib/worksheet-runtime-library.jar:/home/dnguyen/workspace2/myworksheet/bin:/home/dnguyen/ScalaIDE/eclipse/plugins/org.scala-ide.scala211.jars_4.6.1.201706090853/target/jars/scala-reflect.jar
-d
/home/dnguyen/workspace2/myworksheet/.worksheet/bin
2017-07-19 10:19:40,410  INFO [org.eclipse.jface.text.reconciler.MonoReconciler] - ScalaPresentationCompiler - Clearing doc comments (0 entries)
2017-07-19 10:19:40,410  INFO [org.eclipse.jface.text.reconciler.MonoReconciler] - ScalaPresentationCompiler - Flushed hellows.sc`
`

`Scala IDE version:
        4.6.1.v-2_12-201706090854-f511faf
Scala compiler version:
        2.12.2
Scala library version:
        2.12.2
Eclipse version:
        4.6.3.v20170301-0400
Class loader store: 2 entries
        Compiler v. 2.12.2(/home/dnguyen/ScalaIDE/eclipse/plugins/org.scala-lang.scala-compiler_2.12.2.v20170412-161608-VFINAL-21d12e9.jar)
	Compiler v. 2.11.8(/home/dnguyen/ScalaIDE/eclipse/plugins/org.scala-ide.scala211.jars_4.6.1.201706090853/target/jars/scala-compiler.jar)
`

**Comment by wpopielarski** [comment]
Currently I'm on vacation but I try to look at it at the end of July

Regards
W.

2017-07-19 16:27 GMT+02:00 DungxNguyen <notifications@github.com>:

**Comment by DungxNguyen** [comment]
@wpopielarski Did you take a look at it?

Best,
Dung

**Comment by wpopielarski** [comment]
I looked into it. It's not so easy. As Iulian mentioned on gitter worksheet
is not designed to run with another but scala ide scala version. So plan is
to make scala dependent worksheet bundles and select appropriate with
project's scala version. This will allow to compile and run snippet with
correct scala. The only thing which won't be fixed is presentation compiler
version. So you could get some squiggles in code but with correct output.
My estimate to implement it is 3 to 4 weeks. So including a time for
current release some 2 to 3 weeks I could expect "multi scala worksheet" in
first week of October.
W.

2017-08-20 1:34 GMT+02:00 DungxNguyen <notifications@github.com>:

**Comment by wpopielarski** [comment]
Starting to work on it

**Comment by wpopielarski** [comment]
I managed to replace worksheet `ResidentCompiler` by its version in `scala-ide.core` which is found on Zinc so supports scala multi version. Estimated time to finish 3-4 days.

**Comment by wpopielarski** [comment]
https://github.com/scala-ide/scala-worksheet/pull/236

**Comment by wpopielarski** [comment]
ready for code inspection
