### ISSUE TITLE
Worksheet process has terminated unexpectedly (exit value 143

### ISSUE THREAD

**Issue by vutbao** [scala-ide/scala-worksheet#237]
Hi,

I can't seem to get the scala worksheet working.  I cannot save changes nor see any evaluating.

ERROR [Worker-1] - ProgramExecutor$ - Worksheet process has terminated unexpectedly (exit value 143
At the time of termination, the following text was available in the output streams:
Standard output:
  
Standard error:

------
My specs
Eclipse: Neon 3 (Release 4.6.3)
Scala IDE: 4.6.1.v-2_12-201706090854-f511faf
Scala Worksheet: 0.7.0.v-2_12-201706090917-9b473a6

Thanks,

**Comment by wpopielarski** [comment]
could you share your project (its minimal version) and its settings
(especially if you are working with scala 2.11 or 2.12) as well please?

2017-09-29 8:06 GMT+02:00 vutbao <notifications@github.com>:

**Comment by vutbao** [comment]
![image](https://user-images.githubusercontent.com/5642026/31003475-bc7835fe-a4a4-11e7-855a-6cdcc0ecfb78.png)

![image](https://user-images.githubusercontent.com/5642026/31003583-4ea6b9e6-a4a5-11e7-88cc-2eb6481da2cf.png)

**Comment by vutbao** [comment]
Let me know if if there is specifiec debug information you're looking for.
Thanks,

**Comment by vutbao** [comment]
The project is just a hello-world with a worksheet. 
![image](https://user-images.githubusercontent.com/5642026/31003706-e7d720c4-a4a5-11e7-968f-2d92e0f06e2b.png)

**Comment by wpopielarski** [comment]
you can try to open `Scala -> Open the Log` and look there for any trace of
error.

2017-09-29 8:36 GMT+02:00 vutbao <notifications@github.com>:

**Comment by wpopielarski** [comment]
really hard to say. today or Monday we are planing to release 4.7.0 with no
changes in comparison to 4.7.0 RC1. So if you are in hurry you can try this
guy http://scala-ide.org/download/milestone.html. Looks like there is no
problem

2017-09-29 8:58 GMT+02:00 Wieslaw Popielarski <wpopielarski@gmail.com>:

**Comment by vutbao** [comment]
Below is the content of the scala-ide.log (from when I started Eclipse IDE to when I unsuccessfully saved the worksheet (by clicking the 'Save' icon and finally closed the worksheet)
------
2017-09-29 00:07:44,715  WARN [main] - ScalaProject - Project LearningScala has platform default sourceLevel.
2017-09-29 00:07:44,717  WARN [main] - ScalaProject - Project LearningScala runs on platform default installation.
2017-09-29 00:07:44,730  WARN [main] - ScalaProject - Project LearningScala has platform default sourceLevel.
2017-09-29 00:07:44,730  WARN [main] - ScalaProject - Project LearningScala runs on platform default installation.
2017-09-29 00:08:59,239 ERROR [Worker-13] - ProgramExecutor$ - Worksheet process has terminated unexpectedly (exit value 143
At the time of termination, the following text was available in the output streams:
Standard output:
  
Standard error:

**Comment by wpopielarski** [comment]
you can try also to switch scala installation to `Fixed Scala Installation:
2.12.2 (built in)`

2017-09-29 9:10 GMT+02:00 Wieslaw Popielarski <wpopielarski@gmail.com>:

**Comment by wpopielarski** [comment]
i see, nothing there...

2017-09-29 9:12 GMT+02:00 vutbao <notifications@github.com>:

**Comment by vutbao** [comment]
Switched to 'Fixed Scala Installation: 2.12.2 (built in)'
The issue is still there.  Info logged to the log:
2017-09-29 00:17:58,272 ERROR [main] - org.scala-ide.sdt.core - org.scala-ide.sdt.core - org.scala-ide.sdt.core - 0 - scala.MatchError: ScalaInstallationChange() (of class org.scalaide.core.ScalaInstallationChange)

**Comment by vutbao** [comment]
Switch to 'Fixed Scala Installation: 2.11.8 (built in)'
and tried to save

2017-09-29 00:21:15,149 ERROR [Worker-26] - ProgramExecutor$ - Worksheet process has terminated unexpectedly (exit value 1
At the time of termination, the following text was available in the output streams:
Standard output:
  
Standard error:
  Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcV$sp
        at Worksheet1$.main(Worksheet1.scala:1)
        at Worksheet1.main(Worksheet1.scala)
Caused by: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcV$sp
        ... 2 more
Caused by: java.lang.ClassNotFoundException: scala.runtime.java8.JFunction0$mcV$sp
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more

**Comment by wpopielarski** [comment]
worksheet with other than 2.12 is not working now. Here is PR to fix it
https://github.com/scala-ide/scala-worksheet/pull/236. Unfortunately
worksheet wasn't designed to support many versions.

2017-09-29 9:24 GMT+02:00 vutbao <notifications@github.com>:

**Comment by wpopielarski** [comment]
could you just download scala ide 4.6.1 version and try on this new one? It
works ok for me. Looks like something is corrupted and maybe it is problem
with update site link.

2017-09-29 9:35 GMT+02:00 Wieslaw Popielarski <wpopielarski@gmail.com>:

**Comment by wpopielarski** [comment]
I don't mean link, I mean the way how products like worksheet, play, search
and so on are assembled in the package

2017-09-29 9:40 GMT+02:00 Wieslaw Popielarski <wpopielarski@gmail.com>:

**Comment by vutbao** [comment]
It's 12:42AM my time (PDT) and I'm exhausted.  I'll try it tomorrow.  Thank you for your help!

**Comment by wpopielarski** [comment]
sorry for inconvenience, have a good night

2017-09-29 9:44 GMT+02:00 vutbao <notifications@github.com>:

**Comment by wpopielarski** [comment]
I'm really very surprised with this guy:

Switched to 'Fixed Scala Installation: 2.12.2 (built in)'
The issue is still there. Info logged to the log:
2017-09-29 00:17:58,272 ERROR [main] - org.scala-ide.sdt.core -
org.scala-ide.sdt.core - org.scala-ide.sdt.core - 0 - scala.MatchError:
ScalaInstallationChange() (of class org.scalaide.core.
ScalaInstallationChange)


2017-09-29 9:41 GMT+02:00 Wieslaw Popielarski <wpopielarski@gmail.com>:

**Comment by BMounika** [comment]
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/14194091/33122535-7fe70c0e-cf9d-11e7-9ea5-ff971b3d9803.PNG">


Unable to save worksheet...Could you please help me on this?

**Comment by wpopielarski** [comment]
just curious if you could switch to 2.11.11 and check?

2017-11-22 11:25 GMT+01:00 BMounika <notifications@github.com>:

**Comment by wpopielarski** [comment]
looks like this is a problem with bigger worksheet files. Some race
comdition between compiler and actors. Looking into...

2017-11-22 11:51 GMT+01:00 Wieslaw Popielarski <wpopielarski@gmail.com>:
